Bootstrap: docker
From: ubuntu:20.04

%labels
MAINTAINER TRF

%files

%environment
    
%post
    apt-get update
    apt-get install -y pwgen
    apt-get install -y git recoll python3-recoll recollcmd recollgui
%runscript
    exec "$@"
